version: '3.8'

services:
  web:
    build: ./Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      - MYSQL_HOST=db
      # Другие переменные для подключения к MySQL

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=<пароль>
      - MYSQL_DATABASE=<название_бд>
      - MYSQL_USER=<пользователь>
      - MYSQL_PASSWORD=<пароль_пользователя>
    env_file:
      - .env

networks:
  backend:

include:
  - ./proxy.yaml
