version: '3.8'
services:
  web:
    build: .
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10

include:
  - proxy.yaml

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
