version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.python
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=QwErTy1234
      - MYSQL_DATABASE=virtd
    depends_on:
      - db  # Указываем зависимость от сервиса базы данных
  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      MYSQL_ROOT_PASSWORD: YtReWq4321

include:
  - proxy.yaml

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
